"""add is_public to junto

Revision ID: 1386dda8d17b
Revises: e2f3a4b5c6d7
Create Date: 2026-03-19 09:24:59.925151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1386dda8d17b'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_commitment_member_week'), 'commitment', type_='unique')
    op.add_column('junto', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'member', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('user_timezone', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('notification_prefs', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('chatbot_msgs_used', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('chatbot_addon', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('subscription_tier', sa.Enum('free', 'standard', 'expanded', name='subscriptiontier'), nullable=False))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'stripe_subscription_id')
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'subscription_tier')
    op.drop_column('user', 'chatbot_addon')
    op.drop_column('user', 'chatbot_msgs_used')
    op.drop_column('user', 'notification_prefs')
    op.drop_column('user', 'last_active_at')
    op.drop_column('user', 'location')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'user_timezone')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('junto', 'is_public')
    op.create_unique_constraint(op.f('uq_commitment_member_week'), 'commitment', ['member_id', 'cycle_week'])
    # ### end Alembic commands ###
