"""add_meeting_attendance_and_junto_tier

Revision ID: c44433b1879f
Revises: f8a5594ef175
Create Date: 2026-02-12 08:25:35.842055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44433b1879f'
down_revision: Union[str, Sequence[str], None] = 'f8a5594ef175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('junto_id', sa.Integer(), nullable=False),
    sa.Column('held_on', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['junto_id'], ['junto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    juntotier = sa.Enum('FREE', 'SUBSCRIPTION', 'EXPANDED', name='juntotier')
    juntotier.create(op.get_bind(), checkfirst=True)
    op.add_column('junto', sa.Column('tier', juntotier, nullable=False, server_default='FREE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('junto', 'tier')
    sa.Enum(name='juntotier').drop(op.get_bind(), checkfirst=True)
    op.drop_table('meeting_attendance')
    op.drop_table('meeting')
    # ### end Alembic commands ###
